dataset: # dataset to run benchmark on
  - simulated
  - MEG

solver: # list of example solvers to do benchmark
  - CPU
  - CuPy
  - sklearn
  - skglm
  - Numba
  - Jax

# note: use more repetitions to have quantiles on the plot
n-repetitions: 1
max-runs: 1000
timeout: 60
n-jobs: 1
