objective:
  - Lasso Regression[fit_intercept=False,reg=0.1]
  - Lasso Regression[fit_intercept=False,reg=0.01]

dataset: # dataset to run benchmark on
  - leukemia
  - libsvm
  - MEG
  - Simulated

solver: # list of example solvers to do benchmark
  - skglm
  - cd-aa
  - cd

# note: use more repetitions to have quantiles on the plot
n-jobs: 15
n-repetitions: 1
max-runs: 100
