dataset: # dataset to run benchmark on
  - Simulated

solver: # list of example solvers to do benchmark
  - skglm
  # - anderson-cd-jax
  - jax-opt-cd-aa
  - fista-jax

# note: use more repetitions to have quantiles on the plot
n-repetitions: 1
max-runs: 100
