objective:
  - Lasso Regression[fit_intercept=False,reg=0.1]

dataset: # dataset to run benchmark on
  - simulated

solver: # list of example solvers to do benchmark
  - python-pgd
  - sklearn
  - skglm
  - L-BFGS-B
  - cd

# note: use more repetitions to have quantiles on the plot
n-repetitions: 1
max-runs: 10000
n-jobs: 10
