dataset: # dataset to run benchmark on
  - simulated
  - MEG
  - libsvm
  # - finance

solver: # list of example solvers to do benchmark
  # - CPU
  # - CuPy
  - skglm
  # - Numba
  - Jax
  - FyTorch

# note: use more repetitions to have quantiles on the plot
n-repetitions: 1
max-runs: 1000
timeout: 120
n-jobs: 1
